"""empty message

Revision ID: 95c6431702c6
Revises: 
Create Date: 2026-06-16 10:02:56.485672
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '95c6431702c6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('balance', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('btc', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('btc_amount', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('entry_usd_amount', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('entered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('exit_price', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('exit_usd_amount', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('exited_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trades')
    op.drop_table('companies')
    # ### end Alembic commands ###
